const BASE_DATA = window.CA_DATA || [];
const PROGRESS_KEY = "ca_vault_progress_v1";
const CUSTOM_KEY = "ca_vault_custom_data_v1";
let customData = JSON.parse(localStorage.getItem(CUSTOM_KEY) || "[]");
let progress = JSON.parse(localStorage.getItem(PROGRESS_KEY) || "{}");
let view = "all";
let flashIndex = 0;
let flashPool = [];
let calendarDate = new Date();

const $ = id => document.getElementById(id);
const pad = n => String(n).padStart(2, "0");
const today = () => { const d = new Date(); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; };
const monthName = date => new Intl.DateTimeFormat("en-IN", { month:"long" }).format(new Date(`${date}T12:00:00`));
const DATA = () => [...BASE_DATA, ...customData];
const save = (rerender = true) => { localStorage.setItem(PROGRESS_KEY, JSON.stringify(progress)); if (rerender) render(); };
const saveCustom = (rerender = true) => { localStorage.setItem(CUSTOM_KEY, JSON.stringify(customData)); if (rerender) { populate(true); render(); } };

function getState(id) { return progress[id] || { status:"new", important:false, reviews:0, due:null, wrong:0, lastWrong:null }; }
function esc(s) { return String(s ?? "").replace(/[&<>"']/g, m => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])); }
function cleanText(s) { return String(s || "").replace(/\s+/g, " ").trim(); }
function firstSentence(s) { const t=cleanText(s).replace(/\s*\.\s*/g,". "); const m=t.match(/^(.{45,260}?[.!?])(?:\s|$)/); return (m?m[1]:t.slice(0,220)).trim(); }
function dueCount() { return DATA().filter(x => { const s=getState(x.id); return s.due && s.due<=today() && s.status!=="mastered"; }).length; }
function learnedCount() { return DATA().filter(x => { const s=getState(x.id); return s.status==="learned" || s.status==="mastered"; }).length; }
function weakCount() { return DATA().filter(x => getState(x.id).wrong>0 && getState(x.id).status!=="mastered").length; }
function stats() {
  const data=DATA(), c={new:0,remember:0,learned:0,mastered:0,important:0};
  data.forEach(x=>{const s=getState(x.id); c[s.status]=(c[s.status]||0)+1; if(s.important)c.important++;});
  $("stats").innerHTML=[["📚",data.length,"Total CA"],["🆕",c.new,"New"],["🔴",c.remember,"Need to Remember"],["🟡",dueCount(),"Review Today"],["🟢",learnedCount(),"Learned"],["⭐",c.important,"Must Remember"],["⚠️",weakCount(),"Weak CA"],["⚡",dailyPool().length,"Daily Revision"]].map(a=>`<div class="stat"><b>${a[0]} ${a[1]}</b><span>${a[2]}</span></div>`).join("");
}
function populate(force=false) {
  if(force){ $("month").innerHTML='<option value="">All months</option>'; $("category").innerHTML='<option value="">All categories</option>'; }
  const data=DATA();
  [...new Set(data.map(x=>x.month).filter(Boolean))].forEach(x=>{if(![...$("month").options].some(o=>o.value===x))$("month").insertAdjacentHTML("beforeend",`<option value="${esc(x)}">${esc(x)}</option>`);});
  [...new Set(data.map(x=>x.category).filter(Boolean))].sort().forEach(x=>{if(![...$("category").options].some(o=>o.value===x))$("category").insertAdjacentHTML("beforeend",`<option value="${esc(x)}">${esc(x)}</option>`);});
}
function matches(x) {
  const q=$("search").value.toLowerCase().trim(),m=$("month").value,c=$("category").value,st=$("status").value,s=getState(x.id);
  if(q && !(x.title+" "+x.summary+" "+x.category+" "+x.month+" "+(x.tags||[]).join(" ")).toLowerCase().includes(q))return false;
  if(m&&x.month!==m)return false; if(c&&x.category!==c)return false; if(st&&s.status!==st)return false;
  if(view==="remember"&&s.status!=="remember")return false;
  if(view==="learned"&&s.status!=="learned"&&s.status!=="mastered")return false;
  if(view==="important"&&!s.important)return false;
  if(view==="review"&&!(s.due&&s.due<=today()&&s.status!=="mastered"))return false;
  if(view==="weak"&&!(s.wrong>0&&s.status!=="mastered"))return false;
  if(view==="daily"&&!dailyPool().some(y=>y.id===x.id))return false;
  if(["quiz","flashcards","calendar","add"].includes(view))return false;
  return true;
}
function card(x) {
  const s=getState(x.id),summary=x.summary||"No summary extracted.",short=summary.length>650?summary.slice(0,650)+"…":summary;
  const days=s.reviews===0?1:s.reviews===1?3:s.reviews===2?7:s.reviews===3?14:30;
  const date=x.date?` • ${x.date}`:"";
  const own=x.source==="custom";
  return `<article class="card"><div class="card-head"><div><h3 class="title">${esc(x.title)}</h3><div class="meta">${esc(x.month)}${date} • ${esc(x.category)} ${own?" • ✍️ My CA":""} ${s.important?" • ⭐ Must Remember":""}${s.wrong?` • ⚠️ Wrong ${s.wrong}x`:""}</div></div><div class="due">${s.due?"Review: "+s.due:""}</div></div><div class="summary">${esc(short)}</div><div class="fact"><b>🧠 Recall:</b> Title dekho, answer mind mein bolo, phir exam note kholo. Active recall se yaad rakhna hai.</div><details><summary><b>Show exam note</b></summary><p class="summary">${esc(summary)}</p></details><div class="actions"><button class="action red" onclick="mark('${x.id}','remember')">🔴 Need to Remember</button><button class="action yellow" onclick="mark('${x.id}','review')">🟡 Review in ${days}d</button><button class="action green" onclick="mark('${x.id}','learned')">🟢 I Learned It</button><button class="action star" onclick="toggleImportant('${x.id}')">${s.important?"★ Unmark":"⭐ Must Remember"}</button>${own?`<button class="action delete" onclick="deleteCustom('${x.id}')">🗑 Delete</button>`:""}</div></article>`;
}
function dailyPool(){const data=DATA();const due=data.filter(x=>{const s=getState(x.id);return s.due&&s.due<=today()&&s.status!=="mastered"}),weak=data.filter(x=>{const s=getState(x.id);return s.wrong>0&&s.status!=="mastered"}),important=data.filter(x=>getState(x.id).important&&getState(x.id).status!=="mastered"),learnedRecent=data.filter(x=>{const s=getState(x.id);return(s.status==="learned"||s.status==="mastered")&&s.reviews<=1});const map=new Map();[...due,...weak,...important,...learnedRecent].forEach(x=>map.set(x.id,x));return [...map.values()];}
function renderDaily(){const pool=dailyPool(),due=pool.filter(x=>{const s=getState(x.id);return s.due&&s.due<=today()&&s.status!=="mastered"}).length,weak=pool.filter(x=>getState(x.id).wrong>0).length,important=pool.filter(x=>getState(x.id).important).length,recent=pool.filter(x=>getState(x.id).reviews<=1&&(getState(x.id).status==="learned"||getState(x.id).status==="mastered")).length;$("list").innerHTML=`<div class="daily-box"><h2>⚡ Today's Revision</h2><p>App ne aaj ke liye due, weak, important aur recently learned CA ko ek jagah rakha hai.</p><div class="daily-grid"><div><b>${due}</b><span>Due Today</span></div><div><b>${weak}</b><span>Weak CA</span></div><div><b>${important}</b><span>Must Remember</span></div><div><b>${recent}</b><span>Recently Learned</span></div></div><div class="daily-actions"><button class="primary" onclick="startDailyFlashcards()">🧠 Start Recall</button><button class="secondary" onclick="startDailyQuiz()">📝 Daily Quiz</button></div></div>`+pool.map(card).join("");$("empty").classList.toggle("hidden",pool.length>0);}
function startDailyFlashcards(){flashPool=dailyPool();flashIndex=0;setView("flashcards");}
function startDailyQuiz(){const pool=dailyPool().filter(x=>{const s=getState(x.id);return s.status==="learned"||s.status==="mastered"});if(pool.length<4){alert("Daily Quiz ke liye kam se kam 4 Learned CA chahiye.");return;}window.__quizPoolIds=pool.map(x=>x.id);window.__quizCount=Math.min(10,pool.length);window.__quizCategory="";setView("quiz");}
function hideSpecialPanels(){["quizPanel","flashPanel","calendarPanel","addPanel"].forEach(id=>$(id).classList.add("hidden"));}
function render(){stats();hideSpecialPanels();if(view==="quiz"){$("list").innerHTML="";$("empty").classList.add("hidden");$("quizPanel").classList.remove("hidden");renderQuiz();return;}if(view==="flashcards"){$("list").innerHTML="";$("empty").classList.add("hidden");$("flashPanel").classList.remove("hidden");renderFlashcards();return;}if(view==="calendar"){$("list").innerHTML="";$("empty").classList.add("hidden");$("calendarPanel").classList.remove("hidden");renderCalendar();return;}if(view==="add"){$("list").innerHTML="";$("empty").classList.add("hidden");$("addPanel").classList.remove("hidden");renderAddForm();return;}if(view==="daily"){renderDaily();return;}const arr=DATA().filter(matches);$("list").innerHTML=arr.map(card).join("");$("empty").classList.toggle("hidden",arr.length>0);}
function mark(id,type){let s=getState(id);if(type==="remember"){s.status="remember";s.due=today();}if(type==="learned"||type==="review"){s.status="learned";s.reviews=(s.reviews||0)+1;s.due=addDays(new Date(),s.reviews===1?1:s.reviews===2?3:s.reviews===3?7:s.reviews===4?14:30);}if(s.reviews>=6){s.status="mastered";s.due=addDays(new Date(),30);}progress[id]=s;save();}
function toggleImportant(id){const s=getState(id);s.important=!s.important;progress[id]=s;save();}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`;}
function setView(v){view=v;if(v!=="quiz")window.__quizPoolIds=null;document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.view===v));render();}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>setView(b.dataset.view));["search","month","category","status"].forEach(id=>$(id).addEventListener("input",render));
$("resetBtn").onclick=()=>{if(confirm("Reset all your revision progress? Your added CA entries will NOT be deleted.")){progress={};save();}};

// ---------------- DATA ENTRY ----------------
function renderAddForm(){
  const cats=[...new Set(DATA().map(x=>x.category).filter(Boolean))].sort();
  $("addPanel").innerHTML=`<div class="form-box"><div class="form-head"><div><h2>➕ Add Current Affair</h2><p>September aur future months ki CA yahin se add karo. Date dene par month automatically set ho jayega.</p></div><button class="secondary" onclick="setView('calendar')">📅 Open Calendar</button></div><form id="caForm" class="ca-form"><label>Date <input id="caDate" type="date" value="${today()}" required></label><label>Category <select id="caCategory" required><option value="">Select category</option>${cats.map(c=>`<option>${esc(c)}</option>`).join("")}<option value="__new">+ New category</option></select></label><label>Title <input id="caTitle" type="text" placeholder="Current affair headline" required></label><label>Exam Note / Summary <textarea id="caSummary" rows="7" placeholder="Important facts, numbers, names, place, organisation, etc." required></textarea></label><label>Tags <input id="caTags" type="text" placeholder="e.g. RBI, economy, appointment"></label><label class="check"><input id="caImportant" type="checkbox"> ⭐ Must Remember</label><div class="form-actions"><button class="primary" type="submit">💾 Save CA</button><button class="secondary" type="button" onclick="setView('all')">Cancel</button></div></form><div class="data-note">💡 Added CA browser ke local storage mein save hogi. GitHub/Vercel files change nahi hongi. Isliye same browser/device par entries safe rahengi; future mein export/import bhi add kar sakte hain.</div></div>`;
  $("caCategory").onchange=()=>{if($("caCategory").value==="__new"){const c=prompt("New category name:");if(c&&cleanText(c)){const opt=document.createElement("option");opt.value=cleanText(c);opt.textContent=cleanText(c);$("caCategory").insertBefore(opt,$("caCategory").lastElementChild);$("caCategory").value=cleanText(c);}else $("caCategory").value="";}};
  $("caForm").onsubmit=e=>{e.preventDefault();addCustomCA();};
}
function addCustomCA(){
  const date=$("caDate").value,category=cleanText($("caCategory").value),title=cleanText($("caTitle").value),summary=cleanText($("caSummary").value),tags=cleanText($("caTags").value).split(",").map(x=>cleanText(x)).filter(Boolean);
  if(!date||!category||category==="__new"||!title||!summary){alert("Date, category, title aur exam note required hain.");return;}
  const id=`custom-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  customData.push({id,date,month:monthName(date),category,title,summary,important:false,status:"new",tags:[monthName(date),category,...tags],source:"custom"});
  if($("caImportant").checked)progress[id]={...getState(id),important:true};
  saveCustom(false);save(false);alert("✅ CA save ho gayi!");renderAddForm();
}
function deleteCustom(id){if(!confirm("Is added CA ko delete karna hai?"))return;customData=customData.filter(x=>x.id!==id);delete progress[id];saveCustom(false);save();}

// ---------------- CALENDAR ----------------
function renderCalendar(){
  const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,data=DATA();
  const counts={};data.forEach(x=>{if(x.date)counts[x.date]=(counts[x.date]||0)+1;});
  let cells="";for(let i=0;i<start;i++)cells+='<div class="cal-cell muted"></div>';
  for(let d=1;d<=days;d++){const ds=`${y}-${pad(m+1)}-${pad(d)}`,n=counts[ds]||0,isToday=ds===today();cells+=`<button class="cal-cell day ${isToday?'today':''}" onclick="calendarDay('${ds}')"><span>${d}</span>${n?`<b>${n} CA</b>`:'<small>—</small>'}</button>`;}
  const monthTitle=new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric"}).format(new Date(y,m,1));
  const monthEntries=data.filter(x=>x.date&&x.date.startsWith(`${y}-${pad(m+1)}-`)).sort((a,b)=>a.date.localeCompare(b.date));
  $("calendarPanel").innerHTML=`<div class="calendar-box"><div class="calendar-head"><button class="secondary" onclick="changeCalendar(-1)">← Prev</button><div><h2>📅 ${monthTitle}</h2><p>Daily CA calendar — click a date to see that day's entries.</p></div><button class="secondary" onclick="changeCalendar(1)">Next →</button></div><div class="weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="calendar-grid">${cells}</div><div class="calendar-footer"><b>${monthEntries.length}</b> dated CA in this month. <button class="primary" onclick="setView('add')">➕ Add CA for ${esc(monthTitle)}</button></div>${monthEntries.length?`<div class="calendar-list"><h3>📚 ${monthTitle} Entries</h3>${monthEntries.map(card).join("")}</div>`:`<div class="calendar-empty">No dated CA yet for ${esc(monthTitle)}. Add your daily CA above.</div>`}</div>`;
}
function changeCalendar(n){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+n,1);renderCalendar();}
function calendarDay(ds){const data=DATA().filter(x=>x.date===ds);if(!data.length){$("caDate")?.setAttribute("value",ds);setView("add");setTimeout(()=>{$("caDate").value=ds;},0);return;}$("calendarPanel").innerHTML=`<div class="day-results"><div class="calendar-head"><button class="secondary" onclick="renderCalendar()">← Calendar</button><div><h2>📅 ${ds}</h2><p>${data.length} CA found for this date.</p></div><button class="primary" onclick="setView('add');setTimeout(()=>{if($('caDate'))$('caDate').value='${ds}'},0)">➕ Add Another</button></div>${data.map(card).join("")}</div>`;}

// ---------------- QUIZ ----------------
function learnedPool(){const cat=window.__quizCategory||"",allowed=window.__quizPoolIds?new Set(window.__quizPoolIds):null;return DATA().filter(x=>{const s=getState(x.id);return x.title&&(s.status==="learned"||s.status==="mastered")&&(!cat||x.category===cat)&&(!allowed||allowed.has(x.id));});}
function uniqueOptions(correct,candidates){const out=[],seen=new Set();[correct,...candidates].forEach(v=>{const t=cleanText(v),key=t.toLowerCase();if(t&&!seen.has(key)){seen.add(key);out.push(t);}});return out.slice(0,4);}
function shuffled(a){return [...a].sort(()=>Math.random()-0.5);}
function makeQuestion(x,pool,index){const title=cleanText(x.title),summary=cleanText(x.summary),other=shuffled(pool.filter(y=>y.id!==x.id));let correct=firstSentence(summary)||title;let question=`Which statement correctly matches the current affair: “${title}”?`;let candidates=other.map(y=>firstSentence(y.summary)).filter(v=>v&&v.length>35);const concrete=title.match(/₹\s?[\d,.]+(?:\s?(?:crore|lakh|million|billion))?|\b\d+(?:\.\d+)?%|\b(?:19|20)\d{2}\b/);if(concrete){const token=concrete[0],clean=summary.replace(/\s+/g," "),sentences=clean.split(/(?<=[.!?])\s+/).filter(s=>s.includes(token));if(sentences.length){correct=sentences[0].slice(0,300);question=`According to “${title}”, which statement correctly includes the key figure mentioned in this current affair?`;candidates=other.map(y=>{const ss=cleanText(y.summary).split(/(?<=[.!?])\s+/).find(s=>/₹\s?[\d,.]+|\b\d+(?:\.\d+)?%|\b(?:19|20)\d{2}\b/.test(s));return ss?ss.slice(0,300):firstSentence(y.summary);}).filter(Boolean);}}let options=uniqueOptions(correct,shuffled(candidates));for(const y of other){const fallback=firstSentence(y.summary);if(fallback&&!options.some(o=>o.toLowerCase()===fallback.toLowerCase()))options.push(fallback);if(options.length===4)break;}if(options.length<4){const titleOptions=shuffled(other.map(y=>y.title).filter(Boolean));options=uniqueOptions(correct,[...options,...titleOptions]);}options=shuffled(options.slice(0,4));return{id:`q${index}`,question,correct,options,sourceId:x.id};}
function renderQuiz(){const pool=learnedPool();if(pool.length<4){$("quizPanel").innerHTML=`<div class="quiz-empty"><h2>📝 Learned CA Quiz</h2><p>Quiz start karne ke liye kam se kam <b>4 CA</b> ko <b>🟢 I Learned It</b> mark karo.</p><p>Abhi ${pool.length} Learned/Mastered CA available hain. Quiz mein sirf wahi CA use honge.</p><button class="primary" onclick="setView('all')">📚 Go to All CA</button></div>`;return;}const count=Math.min(parseInt(window.__quizCount||10,10),pool.length,20),selected=shuffled(pool).slice(0,count),questions=selected.map((x,i)=>makeQuestion(x,pool,i+1));$("quizPanel").innerHTML=`<div class="quiz-head"><div><h2>📝 Learned CA Quiz</h2><p>Sirf <b>🟢 Learned / ⭐ Mastered</b> CA se test. Galat answer ko app <b>⚠️ Weak CA</b> mein track karega.</p></div><div class="quiz-controls"><label>Questions <select id="quizCount"><option value="5">5</option><option value="10">10</option><option value="20">20</option></select></label><label>Category <select id="quizCategory"><option value="">All Learned CA</option></select></label><button class="primary" onclick="renderQuiz()">🔄 New Quiz</button></div></div><div class="quiz-score" id="quizScore">Score: 0 / ${questions.length} • Answered: 0 / ${questions.length}</div>${questions.map((q,i)=>`<div class="q" data-source="${esc(q.sourceId)}" data-correct="${esc(q.correct)}"><div class="q-number">Question ${i+1}</div><b>${esc(q.question)}</b><div class="q-source">📌 Source CA: ${esc(selected[i].title)}</div>${q.options.map(o=>`<button class="option" onclick="answerQuiz(this, ${JSON.stringify(q.correct)}, ${JSON.stringify(o)}, ${JSON.stringify(q.sourceId)})">${esc(o)}</button>`).join("")}<div class="answer"></div></div>`).join("")}`;const qc=$("quizCategory");[...new Set(pool.map(x=>x.category))].sort().forEach(x=>qc.insertAdjacentHTML("beforeend",`<option>${esc(x)}</option>`));qc.value=window.__quizCategory||"";qc.onchange=()=>{window.__quizCategory=qc.value;renderQuiz();};const qcount=$("quizCount");qcount.value=String(count);qcount.onchange=()=>{window.__quizCount=Number(qcount.value);renderQuiz();};}
function answerQuiz(btn,correct,given,sourceId){const box=btn.closest(".q"),ans=box.querySelector(".answer");if(box.dataset.done==="1")return;box.querySelectorAll("button.option").forEach(b=>b.disabled=true);const s=getState(sourceId),isCorrect=given===correct;if(isCorrect){btn.classList.add("correct");ans.innerHTML="<div>✅ Correct — fact recalled successfully.</div>";}else{btn.classList.add("wrong");ans.innerHTML="<div>❌ Correct answer: "+esc(correct)+"</div>";s.wrong=(s.wrong||0)+1;s.lastWrong=today();s.due=addDays(new Date(),1);progress[sourceId]=s;}box.dataset.done="1";box.dataset.correctPick=isCorrect?"1":"0";ans.insertAdjacentHTML("beforeend",`<div class="quiz-mark-actions"><span>Mark this CA:</span><button class="mini green" onclick="quizMark('${sourceId}','learned',this)">🟢 Learned</button><button class="mini red" onclick="quizMark('${sourceId}','remember',this)">🔴 Need Revision</button><button class="mini star" onclick="quizImportant('${sourceId}',this)">⭐ Must Remember</button></div>`);localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress));updateQuizScore();stats();}
function updateQuizScore(){const correctCount=[...document.querySelectorAll(".q")].filter(q=>q.dataset.correctPick==="1").length,total=document.querySelectorAll(".q").length,answered=document.querySelectorAll('.q[data-done="1"]').length,el=$("quizScore");if(el)el.textContent=`Score: ${correctCount} / ${total} • Answered: ${answered} / ${total}`;}
function quizMark(id,type,btn){let s=getState(id);if(type==="learned"){s.status="learned";if(!s.due)s.due=addDays(new Date(),1);}if(type==="remember"){s.status="remember";s.due=today();}progress[id]=s;save(false);btn.parentElement.querySelectorAll("button").forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");stats();}
function quizImportant(id,btn){const s=getState(id);s.important=true;progress[id]=s;save(false);btn.classList.add("selected");btn.textContent="⭐ Marked Important";stats();}

// ---------------- FLASHCARDS ----------------
function flashCandidates(){const data=DATA();const weak=data.filter(x=>getState(x.id).wrong>0&&getState(x.id).status!=="mastered"),due=data.filter(x=>{const s=getState(x.id);return s.due&&s.due<=today()&&s.status!=="mastered"}),important=data.filter(x=>getState(x.id).important&&getState(x.id).status!=="mastered"),learned=data.filter(x=>{const s=getState(x.id);return s.status==="learned"||s.status==="mastered"});const map=new Map();[...weak,...due,...important,...learned].forEach(x=>map.set(x.id,x));return [...map.values()];}
function renderFlashcards(){if(!flashPool.length)flashPool=flashCandidates();if(!flashPool.length){$("flashPanel").innerHTML=`<div class="quiz-empty"><h2>🧠 Flashcards</h2><p>Abhi koi CA available nahi hai. Pehle CA ko Learn/Remember mark karo.</p></div>`;return;}const x=flashPool[flashIndex%flashPool.length],s=getState(x.id);$("flashPanel").innerHTML=`<div class="flash-head"><div><h2>🧠 Flashcards</h2><div class="flash-count">${(flashIndex%flashPool.length)+1} / ${flashPool.length}</div></div><button class="secondary" onclick="setView('all')">← Back to CA</button></div><div class="flash-card"><div class="meta">${esc(x.month)} • ${esc(x.category)} ${x.date?`• ${x.date}`:""}</div><h2>${esc(x.title)}</h2><div id="flashAnswer" class="flash-answer hidden">${esc(x.summary)}</div><button class="primary" id="revealBtn">👁 Reveal Exam Note</button></div><div class="flash-actions"><button class="action" onclick="flashPrev()">← Previous</button><button class="action" onclick="flashNext()">Next →</button><button class="action green" onclick="mark('${x.id}','learned');flashNext()">🟢 I Know It</button><button class="action red" onclick="mark('${x.id}','remember');flashNext()">🔴 Need Revision</button><button class="action star" onclick="toggleImportant('${x.id}')">${s.important?"★ Important":"⭐ Must Remember"}</button></div>`;$("revealBtn").onclick=()=>{$("flashAnswer").classList.remove("hidden");$("revealBtn").classList.add("hidden");};}
function flashNext(){if(!flashPool.length)flashPool=flashCandidates();flashIndex=(flashIndex+1)%flashPool.length;renderFlashcards();}
function flashPrev(){if(!flashPool.length)flashPool=flashCandidates();flashIndex=(flashIndex-1+flashPool.length)%flashPool.length;renderFlashcards();}

populate();render();
